### ISSUE TITLE
Questions about DINO self-attention map

### ISSUE THREAD

**Issue by bbhbbxwy** [chwilms/SOS#1]
Hi, I am very interested in reproducing your code, but I am unable to find the download link for the DINO self-attention maps. Could you please provide this link?

**Comment by chwilms** [comment]
Thanks for your comment. The easiest is to produce them yourself, using the official DINO implementation and `visualize_attention.py` script from [here](https://github.com/facebookresearch/dino/blob/main/visualize_attention.py). However, I will try to add the maps to the git soon

**Comment by chwilms** [comment]
@bbhbbxwy [Here are the attention maps for the COCO training set](https://cloud.uni-hamburg.de/s/8xDwPcxJR7FaRwc)
